name: build merge release
on:
  push:
    branches: [ main ]
    tags:
      - "v*"
    paths:
      - 'src/*'
      - 'scripts/*'

jobs:
  build-merge-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
        include:
          - os: macos-latest
            TARGET: macos

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: 'install prerequisites'
        shell: bash
        run: |
          brew install gcc
          brew install opencv
          brew install dlib
          brew install pkg-config
          brew link opencv
          brew link dlib
          pkg-config --modversion opencv4
          pkg-config --modversion dlib-1

      - name: 'compiling simplified up ONNX model'
        shell: bash
        run: |
          /bin/bash scripts/compile-yolo-onnx.sh yolov5s

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - name: 'run tests'
        shell: bash
        env:
          IN_CI: true
        run: |
          make test

      - name: 'package'
        shell: bash
        env:
          IN_CI: true
        run: |
          make archive

      - name: 'make a release'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_RELEASE_TOKEN }}
          automatic_release_tag: ${{ steps.date.outputs.date }}
          prerelease: false
          title: libcv-c-api ${{ steps.date.outputs.date }} release
          files: |
            LICENSE
            build/*.tar.gz
