name: Build and test

on:
  push:
    branches-ignore:
      - master
      - pr/*
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            TARGET: ubuntu
          - os: macos-latest
            TARGET: apple-darwin

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: 'install prerequisites'
        shell: bash
        run: /bin/bash scripts/install-dependencies-on-${{ matrix.TARGET }}.sh
