name: Build and test

on:
  push:
    branches-ignore:
      - main
      - pr/*
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            TARGET: macos

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: 'configure Homebrew cache'
        id: cache
        uses: actions/cache@v3.0.3
        with:
          path: |
            /usr/local/Homebrew
            /usr/local/Cellar
            /usr/local/Frameworks
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: 'install prerequisites: common'
        shell: bash
        run: |
          brew install gcc
          brew install opencv
          brew install dlib
          brew install pkg-config
          brew link opencv
          brew link dlib
          pkg-config --modversion opencv4
          pkg-config --modversion dlib-1

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d')"

      - name: 'package compiled library'
        shell: bash
        run: |
          /bin/bash scripts/package-lib.sh ${{ steps.date.outputs.date }}

      - name: 'package library sources'
        shell: bash
        run: |
          /bin/bash scripts/package-sources.sh ${{ steps.date.outputs.date }}
