name: Build and test

on:
  push:
    branches-ignore:
      - master
      - pr/*
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]
        include:
          - os: ubuntu-latest
            TARGET: ubuntu
          - os: macos-latest
            TARGET: apple-darwin

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 'configure Homebrew cache'
        id: cache
        uses: actions/cache@v3.0.3
        with:
          path: |
            /usr/local/Homebrew
            /usr/local/Cellar
            /usr/local/Frameworks
            /usr/local/bin
            /usr/local/opt
          key: brew-${{ hashFiles('scripts/install-dependencies-on-${{ matrix.TARGET }}.sh') }}
          restore-keys: brew-

      - name: 'install prerequisites'
        shell: bash
        run: /bin/bash scripts/install-dependencies-on-${{ matrix.TARGET }}.sh
        if: steps.cache.outputs.cache-hit != 'true'
