name: Build and test

on:
  push:
    branches-ignore:
      - master
      - pr/*
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04]
        include:
          - os: ubuntu
            TARGET: ubuntu-20.04
          - os: macos-latest
            TARGET: apple-darwin
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: 'install prerequisites'
        run: ./scripts/install-dependencies-on-${TARGET}.sh